services:
  api:
    build: .
    container_name: "confbots-api"
    environment:
      CONFIG_PATH: "./config/local.toml"
    networks:
      - default
      - confbots-net
    ports:
      - "8082:80"
    depends_on:
      - migrate

  postgres:
    image: postgres
    container_name: confbots-api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bots
    ports:
      - "5434:5432"
    volumes:
      - confbots-api_data:/var/lib/postgresql
    networks:
      - default
      - confbots-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/bots?sslmode=disable",
        "up",
      ]

volumes:
  confbots-api_data:

networks:
  confbots-net:
    external: true
