env = "local" #local, dev, prod

[database]
name = "postgres"
host = "postgres"
port = "5432"
user = "postgres"
password = "postgres"
db_name = "bots"

[http_server]
address = "0.0.0.0:80"
timeout = "5s"
idle_timeout = "60s"
